-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgg/F3ehTHZrPVV7rI
QZtPbTGOwmrkcyz6vXOIaxozYyygCgYIKoZIzj0DAQehRANCAAQ6JZNcJnbM6QNQ
yip4P+Wd7SmsSxcArH8dwjCF7exC/fZMPSn+c8XDuAxPwPGthDsMGVhBVlNV4aNe
UNssQxS2
-----END PRIVATE KEY-----